/*
 AP_EMAIL_TD_PROYECTOS
*/
CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TD_PROYECTOS
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 999999999
    NOCACHE;	
CREATE TABLE REPORTUSER.AP_EMAIL_TD_PROYECTOS (
  ID NUMBER(9, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TD_PROYECTOS.NEXTVAL,
  NOMBRE VARCHAR(150) NOT NULL,
  DESCRIPCION VARCHAR(255),
  ACTIVO CHAR(1) NOT NULL,
  PRIMARY KEY (ID)
);

/*
 AP_EMAIL_TD_CORREOS
*/
CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TD_CORREOS
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 999999999
    NOCACHE;	
CREATE TABLE REPORTUSER.AP_EMAIL_TD_CORREOS (
  ID NUMBER(9, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TD_CORREOS.NEXTVAL,
  ID_PROYECTO NUMBER(9, 0) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  NOMBRE VARCHAR(150),
  PASSWORD VARCHAR(150),
  ACTIVO CHAR(1) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_PROYECTO) REFERENCES REPORTUSER.AP_EMAIL_TD_PROYECTOS (ID)
);

/*
 AP_EMAIL_TD_ETAPAS_PROYECTO
*/
CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TD_ETAPAS_PROY
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 999999999
    NOCACHE;
CREATE TABLE REPORTUSER.AP_EMAIL_TD_ETAPAS_PROYECTO (
  ID NUMBER(9, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TD_ETAPAS_PROY.NEXTVAL,
  ID_PROYECTO NUMBER(9, 0) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(255),
  ACTIVO CHAR(1) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_PROYECTO) REFERENCES REPORTUSER.AP_EMAIL_TD_PROYECTOS (ID)
);

/*
 AP_EMAIL_TP_TIPO_CORREO
*/
CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TP_TIPO_CORREO
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 99
    NOCACHE;
CREATE TABLE REPORTUSER.AP_EMAIL_TP_TIPO_CORREO (
  ID NUMBER(2, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TP_TIPO_CORREO.NEXTVAL,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(255),
  ACTIVO CHAR(1) NOT NULL,
  PRIMARY KEY (ID)
);

/*
 AP_EMAIL_TP_TEMPLATES
*/
CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TP_TEMPLATES
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 999999999
    NOCACHE;
CREATE TABLE REPORTUSER.AP_EMAIL_TP_TEMPLATES (
  ID NUMBER(9, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TP_TEMPLATES.NEXTVAL,
  CONTENIDO CLOB NOT NULL,
  ACTIVO CHAR(1) NOT NULL,
  PRIMARY KEY (ID)
);

/*
 AP_EMAIL_TP_VARIABLES
*/
CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TP_VARIABLES
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 999999999999999999
    NOCACHE;
CREATE TABLE REPORTUSER.AP_EMAIL_TP_VARIABLES (
  ID NUMBER(18, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TP_VARIABLES.NEXTVAL,
  ID_TEMPLATE NUMBER(9, 0) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  VALOR VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_TEMPLATE) REFERENCES REPORTUSER.AP_EMAIL_TP_TEMPLATES (ID)
);

/*
 AP_EMAIL_TD_PROY_CORREOS
*/
CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TD_PROY_CORREOS
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    NOCACHE;	
CREATE TABLE REPORTUSER.AP_EMAIL_TD_PROY_CORREOS (
  ID NUMBER(19, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TD_PROY_CORREOS.NEXTVAL,
  ID_ETAPA_PROYECTO NUMBER(9, 0) NOT NULL,
  ID_CORREO NUMBER(9, 0) NOT NULL,
  ID_TIPO_CORREO NUMBER(2, 0) NOT NULL,
  ID_TEMPLATE NUMBER(9, 0),
  FECHA_CREACION TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_ETAPA_PROYECTO) REFERENCES REPORTUSER.AP_EMAIL_TD_ETAPAS_PROYECTO (ID),
  FOREIGN KEY (ID_CORREO) REFERENCES REPORTUSER.AP_EMAIL_TD_CORREOS (ID),
  FOREIGN KEY (ID_TIPO_CORREO) REFERENCES REPORTUSER.AP_EMAIL_TP_TIPO_CORREO (ID),
  FOREIGN KEY (ID_TEMPLATE) REFERENCES REPORTUSER.AP_EMAIL_TP_TEMPLATES (ID)
);

/*
 AP_EMAIL_TD_USUARIOS
*/
CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TD_USUARIOS
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999
    NOCACHE;
CREATE TABLE REPORTUSER.AP_EMAIL_TD_USUARIOS (
  ID NUMBER(4, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TD_USUARIOS.NEXTVAL,
  LOGIN VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(255),
  NOMBRE_EMPRESA VARCHAR(100),
  ACTIVO CHAR(1) NOT NULL,
  FECHA_CREACION TIMESTAMP NOT NULL,
  FECHA_MODIFICACION TIMESTAMP NOT NULL,
  URL_INTEGRACION VARCHAR(255),
  PRIMARY KEY (ID)
);



/*
CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TP_TIPO_ERROR
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999
    NOCACHE;
CREATE TABLE REPORTUSER.AP_EMAIL_TP_TIPO_ERROR (
  ID NUMBER(4, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TP_TIPO_ERROR.NEXTVAL,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(255),
  ACTIVO CHAR(1) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE REPORTUSER.SEQ_AP_EMAIL_TD_PROY_ERROR
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    NOCACHE;
CREATE TABLE REPORTUSER.AP_EMAIL_TD_PROY_ERROR (
  ID NUMBER(19, 0) DEFAULT REPORTUSER.SEQ_AP_EMAIL_TD_PROY_ERROR.NEXTVAL,
  ID_PROYECTO NUMBER(9, 0) NOT NULL,
  ID_CORREO NUMBER(9, 0) NOT NULL,
  ID_TIPO_ENVIO NUMBER(4, 0) NOT NULL,
  ID_TIPO_ERROR NUMBER(4, 0) NOT NULL,
  FECHA_CREACION TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_PROYECTO) REFERENCES REPORTUSER.AP_EMAIL_TD_PROYECTOS (ID),
  FOREIGN KEY (ID_CORREO) REFERENCES REPORTUSER.AP_EMAIL_TD_CORREOS (ID),
  FOREIGN KEY (ID_TIPO_ENVIO) REFERENCES REPORTUSER.AP_EMAIL_TP_TIPO_ENVIO (ID),
  FOREIGN KEY (ID_TIPO_ERROR) REFERENCES REPORTUSER.AP_EMAIL_TP_TIPO_ERROR (ID)
);
*/
